add_newline = false
format = "$directory$character"
palette = "catppuccin_latte"
right_format = "$all"
command_timeout = 1000

[character]
vicmd_symbol = "[N] >>>"
success_symbol = "[➜](bold green)"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style)"

[git_status]
conflicted = "═╬═"
ahead = "⇡"
behind = "⇣"
staged = "●"
modified = "✚"
renamed = "➜"
deleted = "✖"
untracked = "…"

[palettes.catppuccin_latte]
rosewater = "#dc878"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb4"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0b4"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9f"
crust = "#dce0e8"
